### DISCUSSION TITLE
Does ordering still work to specify one plugin per envoy filter

### DISCUSSION THREAD

**Discussion by wonderflow** [mosn/htnn#763] [Q&A]
From my understanding, htnn support specify multiple plugins inside one envoy filter, so multiple plugins can have [ordering features](https://github.com/mosn/htnn/blob/main/site/content/en/docs/developer-guide/plugin_development.md#plugin-order).

```yaml
                http_filters:
                  - name: htnn.filters.http.golang
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
                      library_id: fm
                      library_path: /etc/libgolang.so
                      plugin_name: fm
                      plugin_config:
                        "@type": type.googleapis.com/xds.type.v3.TypedStruct
                        value:
                          plugins:
                            - name: plugin-1
                              config:
                                host_name: Jack
                            - name: plugin-2
```

My question here is, if we use multiple envoy filters like below, does the inherent ordering still work even for plugin specified in different envoy filters?

```yaml
                http_filters:
                  - name: htnn.filters.http.golang
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
                      library_id: fm-01
                      library_path: /etc/libgolang.so
                      plugin_name: fm-01
                      plugin_config:
                        "@type": type.googleapis.com/xds.type.v3.TypedStruct
                        value:
                          plugins:
                            - name: plugin-1
                              config:
                                host_name: Jack
                  - name: htnn.filters.http.golang
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
                      library_id: fm-02
                      library_path: /etc/libgolang.so
                      plugin_name: fm-02
                      plugin_config:
                        "@type": type.googleapis.com/xds.type.v3.TypedStruct
                        value:
                          plugins:
                            - name: plugin-2
```
